# Generated by Django 4.2.29 on 2026-03-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsigliatiCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('immagine_url', models.URLField(max_length=500, verbose_name='URL immagine')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Card Consigliati per te',
                'verbose_name_plural': 'Card Consigliati per te',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='CDI', max_length=100, verbose_name='Badge')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('sottotitolo', models.TextField(verbose_name='Sottotitolo')),
                ('cta_testo', models.CharField(default='Prenota ora', max_length=50, verbose_name='Testo bottone')),
                ('cta_link', models.CharField(default='/cerca', max_length=200, verbose_name='Link bottone')),
                ('immagine_url', models.URLField(max_length=500, verbose_name='URL immagine')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Slide Hero',
                'verbose_name_plural': 'Slide Hero',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='PercheSceglierciSezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(default='Perché sceglierci', max_length=200, verbose_name='Titolo sezione')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('immagine_sfondo_url', models.URLField(max_length=500, verbose_name='URL immagine sfondo')),
            ],
            options={
                'verbose_name': 'Sezione Perché Sceglierci',
                'verbose_name_plural': 'Sezione Perché Sceglierci',
            },
        ),
        migrations.CreateModel(
            name='SalutePerTeArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('Consigli e approfondimenti', 'Consigli e approfondimenti'), ('News', 'News'), ('Comunicati stampa', 'Comunicati stampa'), ('Articoli', 'Articoli')], max_length=50, verbose_name='Tab')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('immagine_url', models.URLField(max_length=500, verbose_name='URL immagine')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Articolo Salute per te',
                'verbose_name_plural': 'Articoli Salute per te',
                'ordering': ['tab', 'ordine'],
            },
        ),
        migrations.CreateModel(
            name='PercheSceglierciCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante', models.CharField(choices=[('light', 'Chiara (bianca)'), ('mid', 'Blu medio'), ('dark', 'Blu scuro')], default='light', max_length=10, verbose_name='Variante')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(verbose_name='Descrizione')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='contenuto.perchescegliercisezione')),
            ],
            options={
                'verbose_name': 'Card Perché Sceglierci',
                'verbose_name_plural': 'Card Perché Sceglierci',
                'ordering': ['ordine'],
            },
        ),
    ]
