# Generated by Django 4.2.29 on 2026-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenuto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(help_text='Es: Dott.ssa Ileana Abbiati', max_length=200, verbose_name='Nome completo')),
                ('specializzazione', models.CharField(help_text='Es: Ginecologia e Ostetricia', max_length=300, verbose_name='Specializzazione')),
                ('ruolo', models.CharField(blank=True, help_text='Es: Dirigente Medico - Responsabile ambulatorio', max_length=300, verbose_name='Ruolo / Qualifica')),
                ('foto_url', models.URLField(blank=True, max_length=500, verbose_name='URL foto')),
                ('bio', models.TextField(blank=True, help_text='Testo introduttivo visualizzato nella scheda', verbose_name='Biografia / Presentazione')),
                ('titoli_accademici', models.JSONField(blank=True, default=list, help_text='Lista JSON: [{"anno": "2005", "titolo": "Specializzazione in Ginecologia"}, ...]', verbose_name='Titoli accademici')),
                ('esperienze_professionali', models.JSONField(blank=True, default=list, help_text='Lista JSON: [{"anno": "2010 - presente", "descrizione": "Dirigente medico CDI"}, ...]', verbose_name='Esperienze professionali')),
                ('pubblicazioni', models.TextField(blank=True, help_text='Testo libero su pubblicazioni e attività di ricerca', verbose_name='Pubblicazioni e Ricerca')),
                ('link_prenota', models.CharField(blank=True, default='/cerca', max_length=200, verbose_name='Link prenota')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Scheda Medico',
                'verbose_name_plural': 'Schede Medici',
                'ordering': ['ordine', 'nome_completo'],
            },
        ),
    ]
