# Generated by Django 4.2.29 on 2026-03-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prestazioni', '0001_initial'),
        ('contenuto', '0002_schedamedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedamedico',
            name='medico',
            field=models.OneToOneField(blank=True, help_text='Collega questa scheda al medico nel catalogo prestazioni', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheda_cms', to='prestazioni.medico', verbose_name='Medico collegato'),
        ),
    ]
