# Generated by Django 4.2.29 on 2026-03-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenuto', '0003_schedamedico_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('processing', 'In elaborazione'), ('done', 'Completato'), ('error', 'Errore')], default='pending', max_length=20, verbose_name='Stato')),
                ('filename', models.CharField(max_length=255, verbose_name='Nome file')),
                ('error_message', models.TextField(blank=True, verbose_name='Messaggio errore')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='contenuto.schedamedico')),
            ],
            options={
                'verbose_name': 'Job importazione CV',
                'verbose_name_plural': 'Job importazioni CV',
                'ordering': ['-created_at'],
            },
        ),
    ]
