# Generated by Django 4.2.29 on 2026-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenuto', '0004_cvimportjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIscritto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('data_iscrizione', models.DateTimeField(auto_now_add=True, verbose_name='Data iscrizione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Iscritto newsletter',
                'verbose_name_plural': 'Iscritti newsletter',
                'ordering': ['-data_iscrizione'],
            },
        ),
    ]
