# Generated by Django 4.2.29 on 2026-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codice', models.CharField(blank=True, max_length=50)),
                ('descrizione', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fondo',
                'verbose_name_plural': 'Fondi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('specializzazione', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medici',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ospedale', 'Ospedale'), ('poliambulatorio', 'Poliambulatorio'), ('clinica', 'Clinica'), ('studio', 'Studio medico'), ('altro', 'Altro')], default='poliambulatorio', max_length=50)),
                ('indirizzo', models.CharField(blank=True, max_length=300)),
                ('citta', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('attiva', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Struttura',
                'verbose_name_plural': 'Strutture',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prestazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('codice', models.CharField(blank=True, db_index=True, max_length=50)),
                ('branca', models.CharField(blank=True, choices=[('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('ginecologia', 'Ginecologia'), ('neurologia', 'Neurologia'), ('oculistica', 'Oculistica'), ('ortopedia', 'Ortopedia'), ('otorinolaringoiatria', 'Otorinolaringoiatria'), ('pediatria', 'Pediatria'), ('psichiatria', 'Psichiatria'), ('radiologia', 'Radiologia'), ('urologia', 'Urologia'), ('laboratorio', 'Laboratorio analisi'), ('fisioterapia', 'Fisioterapia'), ('chirurgia', 'Chirurgia'), ('altra', 'Altra branca')], max_length=50)),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo_solvente', models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo per pazienti solventi (€)', max_digits=8, null=True)),
                ('attiva', models.BooleanField(default=True)),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornata_il', models.DateTimeField(auto_now=True)),
                ('fondi', models.ManyToManyField(blank=True, related_name='prestazioni', to='prestazioni.fondo', verbose_name='Fondi che coprono la prestazione')),
                ('medici', models.ManyToManyField(blank=True, related_name='prestazioni', to='prestazioni.medico')),
                ('strutture', models.ManyToManyField(blank=True, related_name='prestazioni', to='prestazioni.struttura')),
            ],
            options={
                'verbose_name': 'Prestazione',
                'verbose_name_plural': 'Prestazioni',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='strutture',
            field=models.ManyToManyField(blank=True, related_name='medici', to='prestazioni.struttura'),
        ),
    ]
