# Generated by Django 4.2.29 on 2026-03-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='struttura',
            name='cap',
            field=models.CharField(blank=True, max_length=10, verbose_name='CAP'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='descrizione',
            field=models.TextField(blank=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL foto'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitudine'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitudine'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='orari',
            field=models.JSONField(blank=True, default=dict, help_text='Es: {"lun_ven": "07:00-20:00", "sab": "07:00-14:00", "dom": "Chiuso"}', verbose_name='Orari'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='provincia',
            field=models.CharField(blank=True, max_length=5, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='struttura',
            name='servizi',
            field=models.TextField(blank=True, help_text='Uno per riga: es. Radiologia, Cardiologia, ...', verbose_name='Servizi disponibili'),
        ),
    ]
